<?php

namespace Jmbermudo\SGR3Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecursoRepository extends EntityRepository
{
}
