prereserva_respuesta_responsable_show:
    pattern:  /respuesta_responsable/{id}
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:respuestaResponsableShow" }
    
prereserva_respuesta_responsable_action:
    pattern:  /respuesta_responsable_action/{id}
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:respuestaResponsable" }