prereserva:
    pattern:  /
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:index" }

prereserva_show:
    pattern:  /{id}/show
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:show" }

prereserva_new:
    pattern:  /new
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:new" }

prereserva_create:
    pattern:  /create
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:create" }
    requirements: { _method: post }

prereserva_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:edit" }

prereserva_update:
    pattern:  /{id}/update
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:update" }
    requirements: { _method: post|put }

prereserva_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JmbermudoSGR3Bundle:PreReserva:delete" }
    requirements: { _method: post|delete }
