#El código de abajo importa las rutas básicas para login y logout de FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#Borrar este mapeo una vez que el sistema enlace con la BBDD de usuarios real
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    
jmbermudo_sgr3:
    resource: "@JmbermudoSGR3Bundle/Resources/config/routing.yml"
    prefix:   /