security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: jmbermudo_sgr3_homepage
            logout:       true
            anonymous:    true
            
        
    access_control:
        #Los demonios controladores SÓLO podrán accederse desde local o siendo administrador
        - { path: ^/daemon/, roles: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: ^/daemon/, roles: ROLE_ADMIN }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Para testear las páginas de error
        - { path: ^/_error/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        #Todas las páginas interiores están protegidas
        - { path: ^/, roles: ROLE_USER }
