jmbermudo_sgr3_homepage:
    path:  /personal
    defaults: { _controller: JmbermudoSGR3Bundle:Default:index }

JmbermudoSGR3Bundle_recurso:
    resource: "@JmbermudoSGR3Bundle/Resources/config/routing/recurso.yml"
    prefix:   /admin/recurso
    
JmbermudoSGR3Bundle_reunion:
    resource: "@JmbermudoSGR3Bundle/Resources/config/routing/reunion.yml"
    prefix:   /reuniones
    
JmbermudoSGR3Bundle_prereservas:
    resource: "@JmbermudoSGR3Bundle/Resources/config/routing/prereserva.yml"
    prefix:   /prereservas

jmbermudo_sgr3_admin_listar_recursos:
    path:   /admin/listarRecursos
    defaults: { _controller: JmbermudoSGR3Bundle:Admin:listarRecursos }
    
jmbermudo_sgr3_index_public:
    pattern: /
    defaults: { _controller: JmbermudoSGR3Bundle:Public:index }

index:
    pattern: /index
    defaults: { _controller: JmbermudoSGR3Bundle:Daemon:index }
