jmbermudo_sgr3_homepage:
    path:  /{name}
    defaults: { _controller: JmbermudoSGR3Bundle:Default:index, name: pepe }

jmbermudo_sgr3_admin_listar_recursos:
    path:   /admin/listarRecursos
    defaults: { _controller: JmbermudoSGR3Bundle:Admin:listarRecursos }