jmbermudo_sgr3_homepage:
    path:  /{name}
    defaults: { _controller: JmbermudoSGR3Bundle:Default:index, name: pepe }

JmbermudoSGR3Bundle_recurso:
    resource: "@JmbermudoSGR3Bundle/Resources/config/routing/recurso.yml"
    prefix:   /admin/recurso
    
JmbermudoSGR3Bundle_reunion:
    resource: "@JmbermudoSGR3Bundle/Resources/config/routing/reunion.yml"
    prefix:   /reuniones

jmbermudo_sgr3_admin_listar_recursos:
    path:   /admin/listarRecursos
    defaults: { _controller: JmbermudoSGR3Bundle:Admin:listarRecursos }