parameters:
#    jmbermudo_sgr3.example.class: Jmbermudo\SGR3Bundle\Example

services:
#    jmbermudo_sgr3.example:
#        class: %jmbermudo_sgr3.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
