parameters:
#    jmbermudo_sgr3.example.class: Jmbermudo\SGR3Bundle\Example

services:

    jmbermudo_user.registration.form.type:
        class: Jmbermudo\SGR3Bundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: jmbermudo_user_registration }
