Jmbermudo\SGR3Bundle\Entity\Reunion:
    properties:
        nombrePublico:
            - NotBlank: { message: "reunion.nombre.not_blank" }
        invitados:
            - Count:
                min: 1
                minMessage: "reunion.invitados.min"
#        pre-reservas:
#            - Count:
#                min: 1
#                max: %max_pre_reservas_reunion%
#                minMessage: "reunion.prereservas.min"
#                maxMessage: "reunion.prereservas.max"